let fnArray = [
  'jd_bean_home',
  'jd_bean_sign',
  'jd_blueCoin',
  'jd_car_exchange',
  'jd_car',
  'jd_cash',
  'jd_club_lottery',
  'jd_crazy_joy',
  'jd_crazy_joy_coin',
  'JD_DailyBonus',
  'jd_dreamFactory',
  'jd_family',
  'jd_joy_feedPets',
  'jd_joy_reward',
  'jd_joy_run',
  'jd_joy_steal',
  'jd_joy',
  'jd_fruit',
  'jd_jdzz',
  'jd_kd',
  'jd_live',
  'jd_lotteryMachine',
  'jd_moneyTree',
  'jd_necklace',
  'jd_nh',
  'jd_nian',
  'jd_nianCollect',
  'jd_pet',
  // 'jd_petTreasureBox',
  'jd_pigPet',
  'jd_plantBean',
  'jd_rankingList',
  'jd_redPacket',
  'jd_shop',
  'jd_small_home',
  'jd_speed',
  'jd_superMarket',
  'jd_syj',
  'jd_unbind',
  'jd_unsubscribe',
  'jx_sign',
  'jd_bean_change',



]
module.exports = {
  fnArray
}