let fnArray = [
  // 'jd_bean_home',
  // 'jd_bean_sign',
  // 'jd_blueCoin',
  // 'jd_car_exchange',
  // 'jd_car',
  // 'jd_cash',
  // 'jd_club_lottery',
  // 'jd_crazy_joy',
  // // 'jd_crazy_joy_coin',
  // 'JD_DailyBonus',
  // 'jd_jdfactory',
  // 'jd_dreamFactory',
  // 'jd_family',
  // 'jd_joy_feedPets',
  // 'jd_joy_reward',
  // 'jd_joy_run',
  // 'jd_joy_steal',
  // 'jd_joy',
  // 'jd_fruit',
  // 'jd_immortal',
  // 'jd_jdzz',
  // 'jd_kd',
  // 'jd_live',
  // 'jd_lotteryMachine',
  // 'jd_moneyTree',
  // 'jd_necklace',
  // // 'jd_nh',
  // 'jd_nian',
  'jd_nianCollect',
  'jd_pet',
  // 'jd_petTreasureBox',
  'jd_pigPet',
  'jd_plantBean',
  'jd_rankingList',
  'jd_redPacket',
  'jd_shop',
  'jd_small_home',
  'jd_speed',
  'jd_superMarket',
  'jd_syj',
  'jd_unbind',
  'jd_unsubscribe',
  'jx_sign',
  'jd_bj',
  'jd_gyec',
  'jd_5g',
  'jd_818',
  'jd_xgyl',
  // 'jd_live_redrain_half',
  // 'jd_live_redrain_nian',
  // 'jd_live_redrain_offical',
  'jd_mh',
  'jd_ms',
  'jd_xg',
  'jd_xxl_gh',
  'jd_xxl',
  'jd_bean_history',



]
module.exports = {
  fnArray
}