app: jd_all
component: scf
inputs:
  description: jd活动
  eip: false
  enableRoleAuth: true
  environment:
    variables:
      TZ: Aisa/Shangehai
  events:
    - timer: #签到 #源头好物红包 #京东超级盒子
        name: beansign_coupon_superbox
        parameters:
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_bean_sign&jd_super_box
    - timer: #东东超市兑换奖品 #摇京豆 #京东汽车兑换
        name: blueCoin_clublottery_carexchange
        parameters:
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_blueCoin&jd_club_lottery&jd_car_exchange&jd_global&jd_global_mh
    - timer: #东东农场 #东东萌宠 #口袋书店 #京喜农场
        name: fruit_pet_bookshop_jxnc
        parameters:
          cronExpression: "0 5 6-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_bookshop&jd_jxnc
    - timer: # 宠汪汪喂食# 宠汪汪# 摇钱树# 京东种豆得豆# 京喜工厂 #东东工厂 #京东炸年兽领爆竹
        name: feedPets_joy_moneyTree_plantBean_dreamFactory_jdfactory_nC
        parameters:
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: jd_joy_feedPets&jd_joy&jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory
    - timer: #宠汪汪积分兑换奖品 #宠汪汪偷好友积分与狗 #点点券 #东东小窝 #京东直播18豆
        name: joyreward_joysteal_necklace_smallhome_live
        parameters:
          cronExpression: "0 0 0-16/8,20 * * * *"
          enable: true
          argument: jd_joy_reward&jd_joy_steal&jd_necklace&jd_small_home&jd_live
    - timer: #京东全民开红包 #进店领豆 #取关京东店铺商品 #注销京东会员卡 #京东抽奖机 #京东汽车 #京东秒秒币 #小鸽有礼 #小鸽有礼2
        name: redPacket_shop_unsubscribe_unbind_lotteryMachine_car_ms_xg
        parameters:
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_lotteryMachine&jd_car&jd_ms&jd_xg&jd_xgyl
    - timer: #京东天天加速 #天天提鹅 #京东炸年兽
        name: speed_daily_egg
        parameters:
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_speed&jd_daily_egg
    - timer: #京东压岁钱抢百元卡
        name: newYearMoney_lottery
        parameters:
          cronExpression: "0 9,12,16,20,21 * * *"
          enable: true
          argument: jd_newYearMoney_lottery&jd_5g&jd_global
    - timer: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #闪购盲盒 #京东年货节 #盲盒抽京豆
        name: beanchange_crazyjoy_rankingList_beanhome_sgmh_nh_immortal_mh
        parameters:
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_rankingList&jd_bean_home&jd_sgmh&jd_nh&jd_mh
    - timer: #金融养猪 #十元街 #京东快递 #京东赚赚 #签到领现金 #京喜签到 #京东炸年兽签到任务 #京东炸年兽AR #京东炸年兽小程序 #京东手机年终奖
        name: pigPet_syj_kd_jdzz_cash_sign_niansign_nianar_nianwechat_fes
        parameters:
          cronExpression: "0 3 1 * * * *"
          enable: true
          argument: jd_pigPet&jd_syj&jd_kd&jd_jdzz&jd_cash&jx_sign&jd_festival
  handler: index.main_handler
  memorySize: 128
  name: jd_all
  namespace: default
  publicAccess: true
  region: ap-guangzhou
  runtime: Nodejs12.16
  src: ./src
  timeout: 900
name: ap-guangzhou_default_jd_all
org: '1301218540'
stage: dev
# When using this configuration file for deployment, make sure the file name is "serverless.yml".
# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md