app: jd_all
component: scf
inputs:
  description: jd活动
  eip: false
  enableRoleAuth: true
  environment:
    variables:
      TZ: Aisa/Shangehai
  events:
    - timer: # 签到 #东东超市兑换奖品 #摇京豆 #京东汽车 #京东汽车兑换
        parameters:
          name: blueCoin_clublottery_car_carexchange
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_bean_sign&jd_blueCoin&jd_club_lottery&jd_car&jd_car_exchange&jd_festival
    - timer: #东东农场 #东东萌宠 #口袋书店 #京喜农场
        parameters:
          name: fruit_pet_bookshop_jxnc
          cronExpression: "0 5 6-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_bookshop&jd_jxnc
    - timer: # 宠汪汪喂食# 宠汪汪# 摇钱树# 京东种豆得豆# 京喜工厂 #东东工厂 #京东炸年兽领爆竹 #joy挂机 #京喜财富岛
        parameters:
          name: feedPets_joy_moneyTree_plantBean_dreamFactory_jdfactory_nC
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: jd_joy_feedPets&jd_joy&jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jd_nianCollect&jd_jxcfd&jd_crazy_joy_coin
    - timer: #宠汪汪积分兑换奖品 #宠汪汪偷好友积分与狗 #点点券 #东东小窝 #京东直播18豆 #集鞭炮赢京豆
        parameters:
          name: joyreward_joysteal_necklace_smallhome_live_firecrackers
          cronExpression: "0 0 0-16/8,20 * * * *"
          enable: true
          argument: jd_joy_reward&jd_joy_steal&jd_necklace&jd_small_home&jd_live&jd_firecrackers
    - timer: #京东全民开红包 #进店领豆 #取关京东店铺商品 #注销京东会员卡 #京东抽奖机
        parameters:
          name: redPacket_shop_unsubscribe_unbind_lotteryMachine
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_unbind&jd_lotteryMachine
    - timer: #京东天天加速 #天天提鹅 #京东炸年兽 #东东超市
        parameters:
          name: speed_daily_egg_nian
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_speed&jd_daily_egg&jd_nian&jd_superMarket
    - timer: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #京东年货节 #京东神仙书院
        parameters:
          name: beanchange_crazyjoy_rankingList_beanhome_nh_immortal
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_rankingList&jd_bean_home&jd_car&jd_nh&jd_immortal&jd_immortal_answer&jd_crazy_joy_coin&jd_xgyl
    - timer: #金融养猪 #十元街 #京东快递 #京东赚赚 #签到领现金 #京喜签到 #京东炸年兽签到任务 #京东炸年兽AR #京东炸年兽小程序
        parameters:
          name: pigPet_syj_kd_jdzz_cash_sign_niansign_nianar_nianwechat
          cronExpression: "0 3 1 * * * *"
          enable: true
          argument: jd_pigPet&jd_syj&jd_kd&jd_jdzz&jd_cash&jx_sign&jd_nian_sign&jd_nian_ar&jd_nian_wechat      
    - timer: #官方直播
        name: jd_live_redrain_offical
        parameters:
          cronExpression: 0 9,11,13,19,20,21,23 * * *
          enable: true
          qualifier: $DEFAULT
          argument: jd_live_redrain_offical&jd_live_redrain_nian
    - timer:
        name: jd_super
        parameters:
          cronExpression: 40 21 * * *
          enable: true
          qualifier: $DEFAULT
          argument: jd_super
  handler: index.main_handler
  memorySize: 128
  name: jd_all
  namespace: default
  publicAccess: true
  region: ap-guangzhou
  runtime: Nodejs12.16
  src: ./src
  timeout: 900
name: ap-guangzhou_default_jd_all
org: '1301218540'
stage: dev
# When using this configuration file for deployment, make sure the file name is "serverless.yml".
# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md